export const GET_RADAR_DATA = 'GET_RADAR_DATA';
export const GET_RADAR_DATA_ERROR = 'GET_RADAR_DATA_ERROR';
export const GET_RADAR_DATA_RECEIVED = 'GET_RADAR_DATA_RECEIVED';
export const RADAR_SELECTED = 'RADAR_SELECTED';
export const ZOOM_CHANGE = 'ZOOM_CHANGE';